CREATE APPLICATION ROLE IF NOT EXISTS APP_USER;

CREATE OR ALTER VERSIONED SCHEMA APP_CODE;
GRANT USAGE ON SCHEMA APP_CODE TO APPLICATION ROLE APP_USER;



CREATE OR REPLACE FUNCTION APP_CODE.REVERSE_STRING(input_str VARCHAR)
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
AS
$$
    return INPUT_STR ? INPUT_STR.split('').reverse().join('') : INPUT_STR;
$$;

GRANT USAGE ON FUNCTION APP_CODE.REVERSE_STRING(VARCHAR) TO APPLICATION ROLE APP_USER;


CREATE OR REPLACE FUNCTION APP_CODE.REVERSE_STRING_PYTHON(input_str VARCHAR)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
HANDLER = 'reverse_string'
AS
$$
def reverse_string(input_str):
    return input_str[::-1] if input_str else input_str
$$;

GRANT USAGE ON FUNCTION APP_CODE.REVERSE_STRING_PYTHON(VARCHAR) TO APPLICATION ROLE APP_USER;


CREATE OR REPLACE SECURE VIEW APP_CODE.CUST_WITH_JS_UDF AS
SELECT 
    CUSTID, 
    NAME AS CUSTNAME, 
    APP_CODE.REVERSE_STRING(NAME) AS REVERSED_CUSTNAME
FROM SHARED_DATA.CUSTOMERS;

GRANT SELECT ON VIEW APP_CODE.CUST_WITH_JS_UDF TO APPLICATION ROLE APP_USER;